# This build file uses template features from YAML so it is generic enough for
# any Bob project. Don't modify it unless you know what you're doing.

# global variables
variables:
  CONDA_ENVS_PATH: "conda-env"
  CONDA_BLD_PATH: "conda-env"


# Definition of our build pipeline order
stages:
  - build
  - deploy
  - pypi


# Build targets
.build_template: &build_job
  stage: build
  before_script:
    - export PATH=$CONDA_FOLDER/bin:$PATH
    - mkdir _ci
    - curl https://curl.haxx.se/ca/cacert.pem > _ci/cacert.pem
    - export CURL_CA_BUNDLE=`pwd`/_ci/cacert.pem
    - export SSL_CERT_FILE=`pwd`/_ci/cacert.pem
    - curl "https://gitlab.idiap.ch/bob/bob.admin/raw/condapackage/gitlab/install.sh" > _ci/install.sh
    - chmod 755 _ci/install.sh
    - ./_ci/install.sh _ci condapackage
  script:
    - ./_ci/build.sh

.build_linux_template: &linux_build_job
  <<: *build_job
  artifacts:
    expire_in: 1 week
    paths:
      - _ci/
      - ${CONDA_ENVS_PATH}/linux-64/*.tar.bz2
  tags:
    - docker
  image: continuumio/conda_builder_linux
  variables: &linux_variables
    CONDA_FOLDER: "/opt/miniconda"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - ${CONDA_ENVS_PATH}/.pkgs/*.tar.bz2
      - ${CONDA_ENVS_PATH}/.pkgs/urls.txt

.build_macosx_template: &macosx_build_job
  <<: *build_job
  artifacts:
    expire_in: 1 week
    paths:
      - _ci/
      - ${CONDA_ENVS_PATH}/osx-64/*.tar.bz2
  tags:
    - macosx
  variables: &macosx_variables
    CONDA_FOLDER: "${CI_PROJECT_DIR}/${CONDA_ENVS_PATH}"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - miniconda.sh
      - ${CONDA_ENVS_PATH}/pkgs/*.tar.bz2
      - ${CONDA_ENVS_PATH}/pkgs/urls.txt


build_linux_27:
  <<: *linux_build_job
  variables:
    <<: *linux_variables
    PYTHON_VERSION: "2.7"

build_linux_35:
  <<: *linux_build_job
  variables:
    <<: *linux_variables
    PYTHON_VERSION: "3.5"

build_linux_36:
  <<: *linux_build_job
  variables:
    <<: *linux_variables
    PYTHON_VERSION: "3.6"
    BUILD_EGG: "true"
  artifacts:
    expire_in: 1 week
    paths:
      - _ci/
      - dist/*.zip
      - sphinx
      - ${CONDA_ENVS_PATH}/linux-64/*.tar.bz2

build_macosx_27:
  <<: *macosx_build_job
  variables:
    <<: *macosx_variables
    PYTHON_VERSION: "2.7"

build_macosx_35:
  <<: *macosx_build_job
  variables:
    <<: *macosx_variables
    PYTHON_VERSION: "3.5"

build_macosx_36:
  <<: *macosx_build_job
  variables:
    <<: *macosx_variables
    PYTHON_VERSION: "3.6"


# Deploy targets
.deploy_template: &deploy_job
  stage: deploy
  before_script:
    - ./_ci/install.sh _ci condapackage
  script:
    - ./_ci/deploy.sh
  dependencies:
    - build_linux_27
    - build_linux_35
    - build_linux_36
    - build_macosx_27
    - build_macosx_35
    - build_macosx_36
  tags:
    - deployer

deploy_beta:
  <<: *deploy_job
  environment: beta
  only:
    - master
    - condapackage

deploy_stable:
  <<: *deploy_job
  environment: stable
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches


pypi:
  stage: pypi
  environment: pypi
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches
  before_script:
    - ./_ci/install.sh _ci condapackage
  script:
    - ./_ci/pypi.sh
  dependencies:
    - build_linux_36
  tags:
    - deployer
